### ISSUE TITLE
[BUG] Update project error

### ISSUE THREAD

**Issue by G-Laliberte** [LabeoTech/Umit#54] opened 2023-02-07 16:56 UTC
**Describe the bug**

I have an error while trying to update the project.

****To Reproduce****

In UmitToolbox main - Astrocytes-v1.5.0

Click on Utilities - Project - Update Project - Full update

error :

Undefined function 'indNwArr' for input arguments of type 'double'.

Error in Protocol/updateList (line 225)
                    newArray(indNwArr(indSubj(i))));

Error in umIToolbox/UpdateprojectMenuSelected (line 1556)
                app.ProtocolObj.updateList(b_discardData);
 
Error using matlab.ui.internal.controller.WebMenuController/fireActionEvent (line 67)
Error while evaluating Menu Callback.

thank you

**Comment by BrunoOFSouza** [comment] 2023-02-07 17:39
Hi @G-Laliberte, 
The issue is fixed in commit 6b9eb9a3bfeddec448d40efe59b2197d03700486. I tested with my dataset and everything works fine now. There was some old pieces of code that were not updated. 

Let us know if the problem persists. 
Thanks for flagging this problem

**Closed by BrunoOFSouza** 2023-02-07 17:39 UTC
Labels: bug
